version: '3.8'
services:
  database:
    container_name: todo-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: todo
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol:
